version: '3.6'
services:
  builder:
    image: node:12
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws:ro
    tmpfs:
      - /build
    working_dir: /app
    command: >
      bash -c '
        npm install -g serverless &&
        cp -ar . /build &&
        rm -rf /build/api/node_modules &&
        rm -rf /build/authorizer/node_modules &&
        cd /build/api && 
        npm install --only=prod &&
        cd /build/authorizer &&
        npm install --only=prod &&
        cd /build &&
        sls --aws-profile hackney deploy'
