version: '3'
services:
  builder:
    image: node:12
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws:ro
    tmpfs:
      - /build
    working_dir: /app
    command: bash -c 'cp -ar /app/* /build && cd /build && rm -r node_modules && npm install --only=prod && npm install -g serverless && sls --aws-profile hackney deploy'
