version: '3'
services:
  builder:
    image: node:12
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws:ro
    tmpfs:
      - /build
    working_dir: /app
    command: bash -O extglob -c 'cp -ar ./!(node_modules|.serverless) /build && cd /build && npm install --only=prod && npm install -g serverless && cd authorizer && npm install --only=prod && cd .. && sls --aws-profile hackney deploy'
