version: '3'
services:
  builder:
    image: node:12
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws:ro
    tmpfs:
      - /build
    working_dir: /app
    command: bash -c 'shopt -s extglob && cp -ar /app/!(node_modules) /build && cd /build && npm install --only=prod && npm install -g serverless && sls --aws-profile hackney deploy'
