service: w2-document-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: production
  profile: hackney
  timeout: 15
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  vpc:
    securityGroupIds:
      - sg-022acccbebd7bca46
    subnetIds:
      - subnet-00356e0650138f74f
      - subnet-0a7f442c22a6feedc

functions:
  w2-document-api:
    name: w2-document-api-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: api/index.handler
    package:
      exclude:
        - '**'
      include:
        - api/index.js
        - api/lib/**
        - api/node_modules/**
    events:
      - http:
          path: '{proxy+}'
          method: ANY
          authorizer: ${self:custom.authorizer.w2-document-api-authorizer}
    environment:
      S3_BUCKET_NAME: w2-documents
      W2_DB_URL: ${ssm:/uhw-document-api/production/W2_DB_URL}
      W2_IMAGE_SERVER_URL: ${ssm:/uhw-document-api/production/W2_IMAGE_SERVER_URL}
      NODE_ENV: production
  w2-document-api-authorizer:
    name: w2-document-api-authorizer-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: authorizer/index.handler
    package:
      exclude:
        - '**'
      include:
        - authorizer/index.js
        - authorizer/node_modules/**
    environment:
      RESOURCE: ${self:custom.apiResource}
      jwtsecret: ${ssm:/common/hackney-jwt-secret}

custom:
  stage: production
  authorizer:
    w2-document-api-authorizer:
      name: w2-document-api-authorizer
      type: REQUEST
      identitySource: method.request.querystring.authToken
      resultTtlInSeconds: 0
  apiResource:
    Fn::Join:
      - ''
      - - 'arn:aws:execute-api:${self:provider.region}:'
        - Ref: 'AWS::AccountId'
        - ':'
        - Ref: 'ApiGatewayRestApi'
        - '/*/*/*'
