version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

jobs:
  build:
    executor: my-executor

    steps:
      - checkout

      - run:
          name: Concatenate all package-lock.json files into single file for checksum
          command: cat package.json api/package.json authorizer/package.json > combined-package-lock.txt

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo npm i && pushd api && npm install && popd && pushd authorizer && npm install && popd

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  test:
    machine: # Docker is available in CircleCI's machine executor
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v12.13 && nvm alias default v12.13
            npm i && pushd api && npm install && popd && pushd authorizer && npm install && popd
      - run:
          name: Run tests with coverage
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v12.13 && nvm alias default v12.13
            sudo docker build -t uh_test_db .
            sudo docker run -dt -p 1433:1433 --name uh_test_db uh_test_db
            pushd api && npm run test-ci && popd

  deploy-staging:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless

      - run:
          name: Set AWS credentials
          command: |
            pushd ~ && serverless config credentials -p aws -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY} -n hackney && popd

      - run:
          name: Deploy application
          command: sls deploy -s staging

  deploy-test:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless

      - run:
          name: Set AWS credentials
          command: |
            pushd ~ && serverless config credentials -p aws -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY} -n hackney && popd

      - run:
          name: Deploy application
          command: sls deploy -s test

  deploy-production:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless

      - run:
          name: Set AWS credentials
          command: |
            pushd ~ && serverless config credentials -p aws -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY} -n hackney && popd

      - run:
          name: Deploy application
          command: sls deploy -s production

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-staging:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy-test:
          requires:
            - deploy-staging
      - permit-deploy-production:
          type: approval
          requires:
            - deploy-staging
      - deploy-production:
          requires:
            - permit-deploy-production
