version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - run:
          name: Set AWS credentials
          command: |
            serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile hackney

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: Run tests with coverage
          command: npm run test-coverage

      - run:
          name: Deploy application
          command: sls deploy
